# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96d4e3cfbd328b092cfdd8c35173636491c191a6eef0b95162225b1194196069bfcc84e91917e34ef66cc147effed83cb5ed2c158f5924bced23fc005b6a8caf

test:
  secret_key_base: bb6556dd019471a17b8bcb7768330ccdebcc91497b6a53abfdd775f0777d1b21349fc8c9e020392af280c2043d4ef161497211a8dd12382d09e4757a05c150f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
