Review.create!([
  {title: "Awesome Lawyers", show: "Suits", author: "Shannon Ching", content: "AWESOME SHOW!!!!!", rating: 7, date_published: "2014-05-22", recommend: "Yes", copy: "Yes"},
  {title: "The Red Wedding", show: "Game of Thrones", author: "Jon Snow", content: "I know nothing.", rating: 2, date_published: "2014-05-23", recommend: "No", copy: "Yes"},
  {title: "Traumatized", show: "Game of Thrones", author: "Lance Putong", content: "This t.v. series is so good! Do not get attached to any of the characters!", rating: 10, date_published: "2014-05-23", recommend: "Yes", copy: "No"},
  {title: "Very Good", show: "Silicon Valley", author: "Justin Bautista", content: "Cool. Geeky", rating: 10, date_published: "2014-05-24", recommend: "Yes", copy: "Yes"}
])
Show.create!([
  {title: "Suits", number_of_seasons: 3, description: "On the run from a drug deal gone bad, Mike Ross, a brilliant college-dropout, finds himself a job working with Harvey Specter, one of New York City's best lawyers.", status: "Finished", episode_length: "42", actors: "Gabriel Macht, Patrick J. Adams, Rick Hoffman, Meghan Markle, Sarah Rafferty, Gina Torres", producers: "Doug Liman, Dave Bartis", rating: 9, poster: "http://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Suits_intertitle.png/800px-Suits_intertitle.png"},
  {title: "Game of Thrones", number_of_seasons: 4, description: "Seven noble families fight for control of the mythical land of Westeros.", status: "Ongoing", episode_length: "55", actors: "Peter Dinklage, Lena Headey, Emilia Clarke, Maisie Williams,  Kit Harington", producers: " David Benioff , D. B. Weiss ,  Frank Doelger ,    Bernadette Caulfield,     Carolyn Strauss ,    George R. R. Martin", rating: 10, poster: "http://www.hbo.com/assets/images/series/game-of-thrones/downloads/wallpaper-iron-throne-1600.jpg"},
  {title: "Silicon Valley", number_of_seasons: 1, description: "Geeky.", status: "Ongoing", episode_length: "28", actors: "", producers: "", rating: 8, poster: "http://www.panicinmyattic.com/wp-content/uploads/2014/04/silicon-valley-s%C3%A9rie.jpg"},
  {title: "Arrow", number_of_seasons: 2, description: "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.", status: "Ongoing", episode_length: "44 ", actors: " Stephen Amell, Katie Cassidy, David Ramsey", producers: "      Greg Berlanti ,    Marc Guggenheim,     Andrew Kreisberg,     David Nutter", rating: nil, poster: "http://www.hdwallpapers.in/download/arrow_tv_series-1280x960.jpg"},
  {title: "The Big Bang Theory", number_of_seasons: 7, description: "A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.", status: "Ongoing", episode_length: "22 mins", actors: " Johnny Galecki, Jim Parsons, Kaley Cuoco", producers: "Chuck Lorre ,Bill Prady Steven, Molaro", rating: nil, poster: "http://georgespigot.files.wordpress.com/2013/12/the-big-bang-08.jpg"}
])
